package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.dto.CheckInInfoDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CheckInInfoMapper {

    /**
     * 根据房间号更新入住状态(0->已入住,1->已退房)
     * @param roomNum
     * @param roomState
     * @return
     */
    int updateCheckInStateByRoomNum(@Param("roomNum") String roomNum,@Param("roomState") Integer roomState);

    /**
     * 查询是否有预定房间
     * @param customerName
     * @param customerPhone
     * @return 订单流水号
     */
    Long queryIsExistsOrder(@Param("customerName") String customerName, @Param("customerPhone") String customerPhone);

    /**
     * 查询客户入住登记次数
     * @param customerName
     * @param customerPhone
     * @return
     */
    int queryCustomerCheckInCount(@Param("customerName") String customerName, @Param("customerPhone") String customerPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long checkInNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    int insert(CheckInInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    int insertSelective(CheckInInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    CheckInInfoDTO selectByPrimaryKey(Long checkInNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckInInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_in_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckInInfoDTO record);
}