package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.FreeRoomCalendar;

public interface FreeRoomCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long freeRoomCalendarNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    int insert(FreeRoomCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    int insertSelective(FreeRoomCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    FreeRoomCalendar selectByPrimaryKey(Long freeRoomCalendarNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FreeRoomCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_room_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FreeRoomCalendar record);
}