package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomOrder;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoomOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insert(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insertSelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    RoomOrder selectByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomOrder record);
}