package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomType;

public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomTypeNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    RoomType selectByPrimaryKey(Long roomTypeNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomType record);
}