package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoomInfoMapper {

    /**
     * 查询房间号(0->未入住,1->已入住)
     * @param roomTypeNum
     * @return
     */
    List<String> selectRoomNumByRoomTypeNum(@Param("roomTypeNum") Long roomTypeNum,
                                             @Param("roomState") Integer roomState);

    /**
     * 更新房间状态(0->未入住,1->已入住)
     * @param roomNum
     * @param roomState
     * @return
     */
    int updateRoomStateByRoomNum(@Param("roomNum") String roomNum,@Param("roomState") Integer roomState);

    /**
     * 查询房间号是否存在
     * @param roomNum
     * @return
     */
    int queryRoomNumIsExists(@Param("roomNum") String roomNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    int insert(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    int insertSelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    RoomInfo selectByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomInfo record);
}