package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomOrder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoomOrderMapper {

    /**
     * 根据顾客姓名获取订单流水号
     * @param customerName
     * @return
     */
    Long selectRoomOrderNumByCustomerName(@Param("customerName") String customerName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insert(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insertSelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    RoomOrder selectByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomOrder record);
}