package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomOrder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoomOrderMapper {

    /**
     * 根据顾客姓名获取订单流水号
     * @param customerName
     * @return
     */
    Long selectRoomOrderNumByCustomerName(@Param("customerName") String customerName);

    /**
     * 更新订单状态
     * @param roomOrderNum
     * @return
     */
    int updateRoomOrderState(@Param("roomOrderNum") Long roomOrderNum,@Param("roomOrderState") Byte roomOrderState);

    /**
     * 查询订单状态
     * @param roomOrderNum
     * @return
     */
    Byte queryOrderState(@Param("roomOrderNum") Long roomOrderNum);

    /**
     * 查询订单是否已入住
     * @param orderNum
     * @return
     */
    Byte findOrderState(Long orderNum);

    /**
     * 取消订单
     * @param orderNum
     * @param orderState
     * @return
     */
    int cancelOrderByNum(@Param("orderNum") Long orderNum,@Param("orderState") Byte orderState);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insert(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insertSelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    RoomOrder selectByPrimaryKey(Long roomOrderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomOrder record);
}