package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomType;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoomTypeMapper {

    /**
     * 根据房间类型名获取房间类型流水号
     * @param roomTypeName
     * @param bedType
     * @return
     */
    Long getRoomTypeNumByRoomTypeNameAndBedType(@Param("roomTypeName") String roomTypeName, @Param("bedType") String bedType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomTypeNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    RoomType selectByPrimaryKey(Long roomTypeNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomType record);
}