package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.model.RoomPrice;

public interface RoomPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomPriceNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    int insert(RoomPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    int insertSelective(RoomPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    RoomPrice selectByPrimaryKey(Long roomPriceNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomPrice record);
}