package com.edu.fjzzit.web.myhotel.mapper;

import com.edu.fjzzit.web.myhotel.dto.RoomOrderDetailAndRoomOrderDTO;
import com.edu.fjzzit.web.myhotel.model.RoomOrder;
import com.edu.fjzzit.web.myhotel.model.RoomOrderDetail;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoomOrderDetailMapper {

    /**
     * 根据订单流水号查询房间类型流水号
     * @param roomOrderNum
     * @return 返回房间类型流水号
     */
    Long queryRoomTypeNumByRoomOrderNum(@Param("roomOrderNum") Long roomOrderNum);

    /**
     * 根据订单流水号查询订房数
     * @param roomOrderNum
     * @return
     */
    int queryRoomCountByRoomOrderNum(@Param("roomOrderNum") Long roomOrderNum);

    List<RoomOrderDetail> findRoomOrderDetailAll(@Param("pageNumber") int pageNumber, @Param("pageSize") int pageSize);

    RoomOrder findRoomOrderByRoomOrderNum(@Param("roomOrderNum")Long roomOrderNum);

    long selCount();

    int updRoomOrderDetailAll(RoomOrderDetailAndRoomOrderDTO roomOrderDetailAndRoomOrderDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roomOrderDetailNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    int insert(RoomOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(RoomOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    RoomOrderDetail selectByPrimaryKey(Long roomOrderDetailNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomOrderDetail record);
}