package com.edu.fjzzit.web.myhotel.model;

public class RoomInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id
     *
     * @mbggenerated
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.building_num
     *
     * @mbggenerated
     */
    private String buildingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_num
     *
     * @mbggenerated
     */
    private String roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_id
     *
     * @return the value of room_info.room_id
     *
     * @mbggenerated
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_id
     *
     * @param roomId the value for room_info.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.building_num
     *
     * @return the value of room_info.building_num
     *
     * @mbggenerated
     */
    public String getBuildingNum() {
        return buildingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.building_num
     *
     * @param buildingNum the value for room_info.building_num
     *
     * @mbggenerated
     */
    public void setBuildingNum(String buildingNum) {
        this.buildingNum = buildingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_num
     *
     * @return the value of room_info.room_num
     *
     * @mbggenerated
     */
    public String getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_num
     *
     * @param roomNum the value for room_info.room_num
     *
     * @mbggenerated
     */
    public void setRoomNum(String roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_type_num
     *
     * @return the value of room_info.room_type_num
     *
     * @mbggenerated
     */
    public Long getRoomTypeNum() {
        return roomTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_type_num
     *
     * @param roomTypeNum the value for room_info.room_type_num
     *
     * @mbggenerated
     */
    public void setRoomTypeNum(Long roomTypeNum) {
        this.roomTypeNum = roomTypeNum;
    }
}