package com.edu.fjzzit.web.myhotel.model;

public class RoomPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_num
     *
     * @mbggenerated
     */
    private Long roomPriceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_name
     *
     * @mbggenerated
     */
    private String roomPriceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.breakfast_type
     *
     * @mbggenerated
     */
    private String breakfastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_price.room_price_num
     *
     * @return the value of room_price.room_price_num
     *
     * @mbggenerated
     */
    public Long getRoomPriceNum() {
        return roomPriceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_price.room_price_num
     *
     * @param roomPriceNum the value for room_price.room_price_num
     *
     * @mbggenerated
     */
    public void setRoomPriceNum(Long roomPriceNum) {
        this.roomPriceNum = roomPriceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_price.room_type_num
     *
     * @return the value of room_price.room_type_num
     *
     * @mbggenerated
     */
    public Long getRoomTypeNum() {
        return roomTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_price.room_type_num
     *
     * @param roomTypeNum the value for room_price.room_type_num
     *
     * @mbggenerated
     */
    public void setRoomTypeNum(Long roomTypeNum) {
        this.roomTypeNum = roomTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_price.room_price_name
     *
     * @return the value of room_price.room_price_name
     *
     * @mbggenerated
     */
    public String getRoomPriceName() {
        return roomPriceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_price.room_price_name
     *
     * @param roomPriceName the value for room_price.room_price_name
     *
     * @mbggenerated
     */
    public void setRoomPriceName(String roomPriceName) {
        this.roomPriceName = roomPriceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_price.breakfast_type
     *
     * @return the value of room_price.breakfast_type
     *
     * @mbggenerated
     */
    public String getBreakfastType() {
        return breakfastType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_price.breakfast_type
     *
     * @param breakfastType the value for room_price.breakfast_type
     *
     * @mbggenerated
     */
    public void setBreakfastType(String breakfastType) {
        this.breakfastType = breakfastType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_price.room_price
     *
     * @return the value of room_price.room_price
     *
     * @mbggenerated
     */
    public Integer getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_price.room_price
     *
     * @param roomPrice the value for room_price.room_price
     *
     * @mbggenerated
     */
    public void setRoomPrice(Integer roomPrice) {
        this.roomPrice = roomPrice;
    }
}