package com.edu.fjzzit.web.myhotel.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_order_detail_num
     *
     * @mbggenerated
     */
    private Long roomOrderDetailNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_order_num
     *
     * @mbggenerated
     */
    private Long roomOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_type_unm
     *
     * @mbggenerated
     */
    private Long roomTypeUnm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_price_name
     *
     * @mbggenerated
     */
    private String roomPriceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.breakfast_type
     *
     * @mbggenerated
     */
    private String breakfastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_count
     *
     * @mbggenerated
     */
    private Integer roomCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.check_in_time
     *
     * @mbggenerated
     */
    private String checkInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.check_out_time
     *
     * @mbggenerated
     */
    private String checkOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order_detail.room_order_detail_price
     *
     * @mbggenerated
     */
    private Integer roomOrderDetailPrice;

}