package com.edu.fjzzit.web.myhotel.model;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_num
     *
     * @mbggenerated
     */
    private Long roomPriceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_name
     *
     * @mbggenerated
     */
    private String roomPriceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.breakfast_type
     *
     * @mbggenerated
     */
    private String breakfastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;

}