package com.edu.fjzzit.web.myhotel.model;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.room_order_num
     *
     * @mbggenerated
     */
    private Long roomOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.customor_name
     *
     * @mbggenerated
     */
    private String customorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.customor_phone
     *
     * @mbggenerated
     */
    private String customorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.room_order_state
     *
     * @mbggenerated
     */
    private Integer roomOrderState;

}