package com.edu.fjzzit.web.myhotel.model;

public class RoomType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_name
     *
     * @mbggenerated
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_type
     *
     * @mbggenerated
     */
    private String bedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_decs
     *
     * @mbggenerated
     */
    private String roomTypeDecs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_type_num
     *
     * @return the value of room_type.room_type_num
     *
     * @mbggenerated
     */
    public Long getRoomTypeNum() {
        return roomTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_type_num
     *
     * @param roomTypeNum the value for room_type.room_type_num
     *
     * @mbggenerated
     */
    public void setRoomTypeNum(Long roomTypeNum) {
        this.roomTypeNum = roomTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_type_name
     *
     * @return the value of room_type.room_type_name
     *
     * @mbggenerated
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_type_name
     *
     * @param roomTypeName the value for room_type.room_type_name
     *
     * @mbggenerated
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.bed_type
     *
     * @return the value of room_type.bed_type
     *
     * @mbggenerated
     */
    public String getBedType() {
        return bedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.bed_type
     *
     * @param bedType the value for room_type.bed_type
     *
     * @mbggenerated
     */
    public void setBedType(String bedType) {
        this.bedType = bedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.floor
     *
     * @return the value of room_type.floor
     *
     * @mbggenerated
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.floor
     *
     * @param floor the value for room_type.floor
     *
     * @mbggenerated
     */
    public void setFloor(String floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_type.room_type_decs
     *
     * @return the value of room_type.room_type_decs
     *
     * @mbggenerated
     */
    public String getRoomTypeDecs() {
        return roomTypeDecs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_type.room_type_decs
     *
     * @param roomTypeDecs the value for room_type.room_type_decs
     *
     * @mbggenerated
     */
    public void setRoomTypeDecs(String roomTypeDecs) {
        this.roomTypeDecs = roomTypeDecs;
    }
}