package com.edu.fjzzit.web.myhotel.model;

import lombok.Data;

@Data
public class RoomInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.building_num
     *
     * @mbggenerated
     */
    private String buildingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_num
     *
     * @mbggenerated
     */
    private String roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    private int roomState;

}