package com.edu.fjzzit.web.myhotel.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_name
     *
     * @mbggenerated
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_type
     *
     * @mbggenerated
     */
    private String bedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_decs
     *
     * @mbggenerated
     */
    private String roomTypeDecs;

}