package com.edu.fjzzit.web.myhotel.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CheckInInfoDTO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.check_in_num
     *
     * @mbggenerated
     */
    private Long checkInNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.customer_phone
     *
     * @mbggenerated
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.roon_num
     *
     * @mbggenerated
     */
    private String roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.customer_ID
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_in_info.check_in_state
     *
     * @mbggenerated
     */
    private Integer checkInState;
}
