package com.edu.fjzzit.web.myhotel.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomInfoRoomTypeRoomPriceDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.building_num
     *
     * @mbggenerated
     */
    private String buildingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_num
     *
     * @mbggenerated
     */
    private String roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * 房间状态
     */
    private int roomState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_name
     * @mbggenerated
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_type
     *
     * @mbggenerated
     */
    private String bedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_decs
     *
     * @mbggenerated
     */
    private String roomTypeDecs;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_name
     *
     * @mbggenerated
     */
    private String roomPriceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.breakfast_type
     *
     * @mbggenerated
     */
    private String breakfastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;
}