package com.edu.fjzzit.web.myhotel.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class RoomTypeAndRoomPriceDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_num
     *
     * @mbggenerated
     */
    private Long roomTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_name
     *
     * @mbggenerated
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.bed_type
     *
     * @mbggenerated
     */
    private String bedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_type.room_type_decs
     *
     * @mbggenerated
     */
    private String roomTypeDecs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price_name
     *
     * @mbggenerated
     */
    private String roomPriceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.breakfast_type
     *
     * @mbggenerated
     */
    private String breakfastType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_price.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;

    public Integer getRoomPrice(){return this.roomPrice;}

}
